commerce_square_catalog.settings:
  type: config_object
  label: 'Commerce Square Catalog settings'
  mapping:
    app_name:
      type: string
      label: 'Application Name'
    sandbox_app_id:
      type: string
      label: 'Sandbox Application ID'
    sandbox_access_token:
      type: string
      label: 'Sandbox Access Token'
    catalog_product_bundle:
      type: string
      label: 'Product Bundle target'
    catalog_stores:
      type: sequence
      label: 'Catalog import stores'
      sequence:
        type: integer
        label: 'Store ID'
