app_name: null
sandbox_app_id: sandbox-sq0idb-x781qoRH63hpT4BDMouivA
sandbox_access_token: EAAAEBgO9n_zsumNHosfHgbos9fWsZ4GIhtgRw227FZgJjK3WzJAW9t4HTYuwuK4
catalog_product_bundle: default
catalog_stores:
  2: 2
  1: 0
