app_name: 'SBA e-Commerce'
app_secret: sandbox-sq0csb-WlUNDQxyRzAgU4z1n_HNNCsvBQQrhZoEn6-uYEhVgUk
sandbox_app_id: sandbox-sq0idb-x781qoRH63hpT4BDMouivA
sandbox_access_token: EAAAEBgO9n_zsumNHosfHgbos9fWsZ4GIhtgRw227FZgJjK3WzJAW9t4HTYuwuK4
production_app_id: sq0idp-UFp00fbXk2sZhQCOb9yW5w
