module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  advancedqueue: 0
  aquila: 0
  automated_cron: 0
  backup_migrate: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  commerce: 0
  commerce_cart: 0
  commerce_checkout: 0
  commerce_currency_resolver: 0
  commerce_exchanger: 0
  commerce_number_pattern: 0
  commerce_order: 0
  commerce_payment: 0
  commerce_price: 0
  commerce_printful: 0
  commerce_product: 0
  commerce_promotion: 0
  commerce_recurring: 0
  commerce_shipping: 0
  commerce_shipstation: 0
  commerce_square: 0
  commerce_square_catalog: 0
  commerce_store: 0
  commerce_stripe: 0
  commerce_tax: 0
  commerce_ups: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_reference_revisions: 0
  field: 0
  field_permissions: 0
  field_ui: 0
  fieldable_path: 0
  file: 0
  filter: 0
  getjwtonlogin: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  inspect: 0
  json_field: 0
  jsonapi: 0
  jsonapi_extras: 0
  jsonapi_hypermedia: 0
  jsonapi_resources: 0
  jwt: 0
  jwt_auth_consumer: 0
  jwt_auth_issuer: 0
  key: 0
  libraries: 0
  link: 0
  mailsystem: 0
  media: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  pathologic: 0
  physical: 0
  profile: 0
  quickedit: 0
  rdf: 0
  rest: 0
  rest_toolkit: 0
  rest_toolkit_commerce: 0
  rest_views: 0
  restui: 0
  search: 0
  search_api: 0
  search_api_db: 0
  serialization: 0
  shortcut: 0
  state_machine: 0
  stripe: 0
  swiftmailer: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  user: 0
  users_jwt: 0
  views_ui: 0
  webform: 0
  webform_devel: 0
  webform_rest: 0
  webform_submission_export_import: 0
  webform_submission_log: 0
  webform_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  claro: 0
  gin: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
