stripe:
  pk_test: pk_test_51IRgSwA198OumERXTSqnEPTHGmYegLQVEh64gvZNHtvTyFhKqXy1ewqKyZwhXZ8PRHxbYMcY9T27l0JhMOdrJ0Gs00zVKkN94W
  sk_test: sk_test_51IRgSwA198OumERXNVD6rWXSaMbAXll6InajHmsl6XEihNz5sObP9WfuVYAAMgNI71qtkTOysB1fXB15LK2deGSr00uqCnjIOK
  pk_live: pk_live_51IRgSwA198OumERX6Un6Ns6woVmIR2i4XdEhbRyPIsG7s0oR92jX6wBoCo2SlBisxOVix3Syi8Pp9ezNsgtVHbox00YmHeE4Uc
  sk_live: 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
  use_test: true
_core:
  default_config_hash: IElAymFtFbov2rg-l6XpceepZ7GDpO4KKQ-y9y4GiM0
